### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iGetUploaded** [DaBlincx/discord-bot-client#3]
After I do *npm i & npm start*  I get this screen not sure whats wrong

![image](https://user-images.githubusercontent.com/54633753/210466567-ed0a26e9-8391-4ef2-81cc-f9e46b26a604.png)

**Comment by DaBlincx** [comment]
did you even read the readme.md? 

the project is not yet finished and not ready fo use

**Comment by Pokenight321** [comment]
bru

**Comment by Pokenight321** [comment]
come back in 1 week it will work
:/
